## Group Support

### Carriers [/api/v1/support/carriers]

#### Show [GET]

+ Response 200 (application/json)

        {
            "data": "tba"
        }

#### Store [POST]

+ Response 200 (application/jshttps://ginja.slack.com/messages/C09T7LD2Qon)

        {
            "data": "tba"
        }

#### Update [PATCH]

+ Request (application/json)

        {
            "data": "tba"
        }

+ Response 200 (application/json)

        {
            "data": "tba"
        }

#### Delete [DELETE]

+ Response 200 (application/json)

        {
            "data": "tba"
        }

### Drivers [/api/v1/support/drivers]

#### Show [GET]

+ Response 200 (application/json)

        {
            "data": "tba"
        }

#### Store [POST]

+ Response 200 (application/json)

        {
            "data": "tba"
        }

#### Update [PATCH]

+ Request (application/json)

        {
            "data": "tba"
        }

+ Response 200 (application/json)

        {
            "data": "tba"
        }

#### Delete [DELETE]

+ Response 200 (application/json)

        {
            "data": "tba"
        }

### Orders [/api/v1/support/orders]

#### All orders [GET]

+ Response 200 (application/json)

        {
            "data": "tba"
        }

#### Get details [GET /api/v1/support/orders/{order_id}]

+ Response 200 (application/json)

        {
            "data": "tba"
        }

#### Update order [PATCH /api/v1/support/orders/{order_id}]

+ Request (application/json)

        {
            "data": "tba"
        }

+ Response 200 (application/json)

        {
            "data": "tba"
        }

#### Assign to staff [POST /api/v1/support/orders/{order_id}/assign]

+ Request (application/json)

        {
            "data": "tba"
        }

+ Response 200 (application/json)

        {
            "data": "tba"
        }

#### Unassign from staff [DELETE /api/v1/support/orders/{order_id}/assign]

+ Response 200 (application/json)

        {
            "data": "tba"
        }

### Order carriers [/api/v1/support/order-carriers]

#### Show [GET]

+ Response 200 (application/json)

        {
            "data": "tba"
        }

#### Store [POST]

+ Response 200 (application/json)

        {
            "data": "tba"
        }

#### Update [PATCH]

+ Request (application/json)

        {
            "data": "tba"
        }

+ Response 200 (application/json)

        {
            "data": "tba"
        }

#### Delete [DELETE]

+ Response 200 (application/json)

        {
            "data": "tba"
        }

### Order notes [/api/v1/support/orders/{order_id}/notes]

#### Get [GET]

+ Response 200 (application/json)

        {
            "data": "tba"
        }

#### Create [POST]

+ Request (application/json)

        {
            "data": "tba"
        }

+ Response 200 (application/json)

        {
            "data": "tba"
        }

### Order products [/api/v1/support/orders/{order_id}/products]

#### Get [GET]

+ Response 200 (application/json)

        {
            "data": "tba"
        }

### Vendors [/api/v1/support/vendors]

#### List [GET /api/v1/support/vendors/all]

+ Response 200 (application/json)

        {
            "data": "tba"
        }


#### Get details [GET /api/v1/support/vendors/{vendor_id}]

+ Response 200 (application/json)

        {
            "data": "tba"
        }


#### Get vendor extra items [GET /api/v1/support/vendors/{vendor_id}/extra-items]

+ Response 200 (application/json)

        {
            "data": "tba"
        }


#### Get vendor extras [GET /api/v1/support/vendors/{vendor_id}/extras]

+ Response 200 (application/json)

        {
            "data": "tba"
        }


### Vendor products [/api/v1/support/vendors/{vendor_id}/products]

#### Get [GET]


+ Response 200 (application/json)

        {
            "data": "tba"
        }

#### Update product [PATCH /api/v1/support/vendors/{vendor_id}/product/{product_id}]

+ Request (application/json)

        {
            "data": "tba"
        }

+ Response 200 (application/json)

        {
            "data": "tba"
        }

### Vendor cart quote [/api/v1/support/vendors/{vendor_id}/carts/quote]

#### Get quote [POST]

+ Request (application/json)

        {
            "data": "tba"
        }

+ Response 200 (application/json)

        {
            "data": "tba"
        }

### Vendor coupon code [/api/v1/support/vendors/{vendor_id}/validate/{code}/{phone}]

#### Check coupon [GET]

+ Response 200 (application/json)

        {
            "data": "tba"
        }

