openapi: 3.0.2
Product:
  type: object
  properties:
    id:
      type: integer
      minimum: 1
    brand_id:
      type: integer
      minimum: 1
      description: tenant ID of the product
    menu_branch_id:
      type: integer
      minimum: 1
      description: Which branch's menu this products belongs to (A product can belong to various branches within the tenant)
    name:
      type: string
      example: 'Candle Numeral 0 pink'
    price:
      type: integer
      minimum: 0
      description: A price in least significant units (ie cents)
    before_sale_price:
      type: integer
      minimum: 0
      nullable: true
      description: A price before discounts applied
    description:
      type: string
      example: 'Pink candle with number zero'
    full_description:
      type: string
      example: 'Pink candle with number zero'
    order:
      type: integer
      minimum: 0
      description: Sorting order, used to arrange products in a certain sequence
    category:
      type: object
      nullable: true
      properties:
        id:
          type: integer
          minimum: 0
        name:
          type: string
          example: 'Soft drinks'
        name_th:
          type: string
          nullable: true
        category_image_src:
          type: string
          format: url
          nullable: true
          example: 'https://images.snpfood.com/image/upload/q_auto/v1/brands/15/inventory/products/4941'
        order:
          type: integer
          minimum: 0
          description: Sorting order
        code:
          type: string
          nullable: true
          description: A unique code of the category, external public identifier from a 3rd party system
    images:
      type: object
      properties:
        original:
          type: string
          format: url
          example: 'https://images.snpfood.com/image/upload/q_auto/v1/brands/15/inventory/products/4941'
          nullable: true
        full_size:
          type: string
          format: url
          example: 'https://images.snpfood.com/image/upload/q_auto/v1/brands/15/inventory/products/4941'
          nullable: true
        thumbnail:
          type: string
          format: url
          example: 'https://images.snpfood.com/image/upload/q_auto/v1/brands/15/inventory/products/4941'
          nullable: true
        thumbnail_retina:
          type: string
          format: url
          example: 'https://images.snpfood.com/image/upload/q_auto/v1/brands/15/inventory/products/4941'
          nullable: true
    extras:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
            minimum: 1
          name:
            type: string
            example: 'Choose your Pie'
          min:
            type: integer
            minimum: 1
            description: The minimum number that can be attached to a product upon a purchase
          max:
            type: integer
            minimum: 1
            description: The miximum number that can be attached to a product upon a purchase
    extra_items:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
            minimum: 1
          name:
            type: string
            example: 'Chicken Pie'
          extra_id:
            type: integer
            minimum: 1
          price:
            type: integer
            minimum: 0
    is_enabled:
      type: boolean
      description: If this product is allowed for purchasing
    has_comments:
      type: boolean
      description: A customer can provided a specific comment related to this product. (ie "no spice please")
    cart_limit:
      type: integer
      minimum: 0
      nullable: true
      description: Max amount of this products allowed to add. 0 - means no limit.
    published_at:
      type: string
      format: timestamp
      nullable: true
      description: When a product should appear to a customer
    unpublished_at:
      type: string
      format: timestamp
      nullable: true
      description: When a product should disappear from a customer's menu
    is_published_on_web:
      type: boolean
      description: If this product allowed to be purchased via Web client
    is_published_on_mobile:
      type: boolean
      description: If this product allowed to be purchased via Mobile client
    is_available_for_pickup:
      type: boolean
      description: If this product allowed to be picked up from the venue
    is_available_for_delivery:
      type: boolean
      description: If this product allowed to be delivered to the customer
    minimum_preorder_days:
      type: integer
      minimum: 0
      nullable: true
      description: The number of days in advance a restaurant needs to deliver/cook
    tags:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
            minimum: 1
          tag:
            type: string
            example: 'Desserts'
    code:
      type: string
      description: A unique vendor's code for the product
      example: 'P-11'
    is_sku_only:
      type: boolean
      description: If true, will not appear on customer menu, but can be purchased through a customer service dashboard
    locales:
      type: object
      additionalProperties:
        type: object
        properties:
          name:
            type: string
          description:
            type: string
      example:
        en: {name: 'Candle Numeral 0 pink', description: 'Pink candle with number zero'}
        th: {name: 'เทียนวันเกิดเลข 0 สีชมพู', description: 'เทียนตัวเลข 0 ขอบชมพู'}
    availability:
      type: string
      enum:
        - available
        - unavailable
        - unknown
      example: available
    variants:
      type: string
      nullable: true
      deprecated: true
    type:
      type: string
      nullable: true
      deprecated: true
