### Customer's addresses [/api/v1/storefront/customers/me/addresses]

If you're offering delivery in some way, shape or form to your customers, they'll need to store one (or multiple) addresses in the system.

#### List all addresses [GET /api/v2/storefront/customers/me/addresses]

Using this endpoint an authenticated customer can retrieve all of their stored addresses.

Note: if lat and lng parameters are provided, it will attach the distance from that location on each address.

+ Request (application/json)

        {
            "lat": "13.730711000000",
            "lng": "100.594267000000"
        }

+ Response 200 (application/json)

        {
            "data": [
                {
                    "address_id": 9909,
                    "type": "others",
                    "building_name": "SSP Building",
                    "room_number": "0",
                    "floor_number": "22",
                    "address1": "Ekkamai rd",
                    "address2": null,
                    "district": "",
                    "city": "Bangkok",
                    "postcode": null,
                    "directions": "Call when you arrive in the foyer",
                    "address_label": null,
                    "latitude": "13.720711000000",
                    "longitude": "100.584267000000",
                    "area_id": null,
                    "geolocation_source": null,
                    "formatted": "SSP Building\nFloor #22\nEkkamai rd\nBangkok",
                    "distance": 20.23
                }
            ]
        }

#### Get address details [GET /api/v1/storefront/customers/me/address/{address_id}]

A customer may also wish to retrieve information about a single address they've previously stored in the system.

+ Response 200 (application/json)

        {
            "data": {
                "address_id": 9909,
                "type": "others",
                "building_name": "SSP Building",
                "room_number": "0",
                "floor_number": "22",
                "address1": "Ekkamai rd",
                "address2": null,
                "district": "",
                "city": "Bangkok",
                "postcode": null,
                "directions": "Call when you arrive in the foyer",
                "address_label": null,
                "latitude": "13.720711000000",
                "longitude": "100.584267000000",
                "area_id": null,
                "geolocation_source": null,
                "formatted": "SSP Building\nFloor #22\nEkkamai rd\nBangkok"
            }
        }

#### Add a new address [POST]

+ Request (application/json)

        {
            "latitude": 13.720711,
            "longitude": 100.584267,
            "building_name": "SSP Building",
            "district": "",
            "address_id": null,
            "floor_number": "22",
            "room_number": "0",
            "address1": "Ekkamai rd",
            "directions": "Call when you arrive in the foyer",
            "type": "others"
        }

+ Response 200 (application/json)

        {
            "data": {
                "address_id": 9909,
                "type": "others",
                "building_name": "SSP Building",
                "room_number": "0",
                "floor_number": "22",
                "address1": "Ekkamai rd",
                "address2": null,
                "district": "",
                "city": null,
                "postcode": null,
                "directions": "Call when you arrive in the foyer",
                "address_label": null,
                "latitude": 13.720711,
                "longitude": 100.584267,
                "area_id": null,
                "geolocation_source": null,
                "formatted": "SSP Building\nFloor #22\nEkkamai rd\n"
            }
        }

#### Update address details [PATCH /api/v1/storefront/customers/me/address/{address_id}]

+ Request (application/json)

        {
            "latitude": 13.720711,
            "longitude": 100.584267,
            "building_name": "SSP Building",
            "district": "Wathanna",
            "floor_number": "22",
            "room_number": "0",
            "address1": "Ekkamai rd",
            "directions": "Call when you arrive in the foyer",
            "type": "others"
        }

+ Response 200 (application/json)

        {
            "address_id": 9909,
            "type": "others",
            "building_name": "SSP Building",
            "room_number": "0",
            "floor_number": "22",
            "address1": "Ekkamai rd",
            "address2": null,
            "district": "Wathanna",
            "city": null,
            "postcode": null,
            "directions": "Call when you arrive in the foyer",
            "address_label": null,
            "latitude": 13.720711,
            "longitude": 100.584267,
            "area_id": null,
            "geolocation_source": null,
            "formatted": "SSP Building\nFloor #22\nEkkamai rd\n"
        }

#### Remove an address [DELETE /api/v1/storefront/customers/me/address/{address_id}]

+ Response 200 (application/json)

        {
            "data": {
                "id": 24717,
                "profile_image_src": null,
                "email": "corey@ginja.co.th",
                "name": "Corey Mcmahon",
                "phone_number": "09428971234",
                "idp": "password",
                "addresses": [],
                "payment_options": null,
                "default_locale": "en",
                "user_id": 21788,
                "customer_facebook_account_id": null,
                "customer_google_account_id": null
            }
        }
