## Group Storefront

The Storefront API enables developers to interact with the "frontend" of the consumer experience. The storefront API exposes inventory information, promotional details (including coupon codes), order status tracking, CRM and notification features (among other things).
