openapi: 3.0.2
info:
  title: Storefront API
  version: 0.0.1
  contact:
    name: Dmitry Lezhnev
    url: /
    email: dmitry@foodkit.io
  x-logo:
    url: "https://cdn.foodkitapp.io/foodkitio/foodkit-logo-white-2x.png"
    backgroundColor: "#FFFFFF"
    altText: "Foodkit logo"
paths:
  # Use this file to set a list of files to merge in
  - $ref: "./inventory/products.yaml"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: string
