### Brands [/api/v3/storefront/brands]

#### List all brands [GET]

+ Response 200 (application/json)

        {
            "data": {
            	"credit_card_gateway": {
            		"name": "2C2P"
            	}
            	"credit_card_gateway_public_key": null
            	"facebook": {
            		"application_id": "999999999999999"
					"redirect_uri": "https://your-restaurant.com/auth/facebook/callback"
				}
				"google": {
					"android_client_id": "549404802555-3Hccctn8cZa2ht4Q3CbHcdTGaGgzZg8E.apps.googleusercontent.com"
					"ios_client_id": "549404802555-ARVjuHwTPyPJyUcwyPMQ4tbDrPZrGNNSs.apps.googleusercontent.com"
					"redirect_uri": "https://delivery.your-restaurant.com/auth/google/callback"
					"web_client_id": "549404802555-FUrAMJ8YDBLvxGqCUuy2Pghhc7eU4UWz.apps.googleusercontent.com"
				}
				"google_browser_key": "p9Ss4hghu2EeNjs8ggUZF3uWZwBySGf6sJnkDfu"
				"id": 9
				"multistore_parent_id": 999
            }
        }

