### Coupon codes [/api/v3/storefront/vendors/{vendor_id}/validate]

The Foodkit platform supports and extensive range of coupon codes which can be used to apply different discounts and incentives for consumers on a targeted or generic basis.

#### Validate coupon code [GET /api/v3/storefront/vendors/{vendor_id}/validate{?code,phone_number}]

Before applying a coupon code to an order, we'll typically want to check its validity.

Note that it's desirable to provide the phone number of the user (if available), as some coupons are limited on a per-phone number basis. It isn't necessary as the quotation and order creation endpoints will also check for this, but it provides a better user experience to check earlier.

+ Parameters
    + code: FREEFOOD (string)
    + phone_number: +66942811234 (string)

+ Response 200 (application/json)

        {
            "data": {
                "id": 648,
                "code": "FREEFOOD",
                "name": "Free Food Coupon",
                "discount_type": "absolute",
                "coupon_type": "promotion",
                "amount": 59.0,
                "reason": "For Internal Usage",
                "is_enabled": 1,
                "usages": 437,
                "max_usages": 0,
                "created_by": 336,
                "created_at": "2016-10-10 03:12:56",
                "updated_at": "2017-09-27 13:06:40",
                "valid_to": null,
                "valid_from": null,
                "deleted_at": null,
                "limit_one_per_phone_number": 0,
                "referrer_phone_number": "",
                "referee_discount_percentage": 0,
                "referrer_discount": 0,
                "vendor_id": null,
                "vendor": null
            }
        }
