     ~ GET    /api/v2/storefront/customers/me/addresses
     ~ POST   /api/v1/storefront/customers/me/addresses
     ~ GET    /api/v1/storefront/customers/me/addresses/{id}
     ~ PATCH  /api/v1/storefront/customers/me/addresses/{id}
     ~ DELETE /api/v1/storefront/customers/me/addresses/{id}
