* Customer
    ~ GET    /api/v1/storefront/customers/me
    ~ PATCH  /api/v2/storefront/customers/me
    ~ POST   /api/v1/storefront/customers/me/
    ~ DELETE /api/v1/storefront/customers/me/card
    ~ POST   /api/v1/storefront/customers/exists
    ~ POST   /api/v3/storefront/password-resets
     ~ POST   /api/v3/storefront/customers/me/push-token
