### Customer loyalty program [/api/v3/storefront/customers/me/loyalty]

#### Get loyalty points [GET]

+ Response 200 (application/json)

        {
            "data": {
            	  "is_member": true
				        "points": 30
            }
        }
