### Customer loyalty program [/api/v3/storefront/customers/me/loyalty]

If the brand has a loyalty program associated with it, you can retrieve the number of "loyalty points" for the logged in user using this endpoint.

Please talk to your Foodkit account manager if you'd like more information about setting up a loyalty program for your brand.

#### Get loyalty points [GET]

+ Response 200 (application/json)

        {
            "data": {
            	  "is_member": true
				        "points": 30
            }
        }
