### Quotations [/api/v3/storefront/vendors/{vendor_id}/carts/quote]

#### Cart quote [POST /api/v3/storefront/vendors/{vendor_id}/carts/quote]

+ Request (application/json)

        {
            "data": "tba"
        }

+ Response 200 (application/json)

        {
            "data": "tba"
        }

#### Calculate delivery cost [GET /api/v1/storefront/vendors/{vendor_id}/delivery-cost]

+ Request (application/json)

        {
            "data": "tba"
        }

+ Response 200 (application/json)

        {
            "data": "tba"
        }


