* Vendor menu
     ~ GET    /api/v1/storefront/vendors/extra-items
     ~ GET    /api/v1/storefront/vendors/{id}/products
     ~ GET    /api/v1/storefront/vendors/{id}/products/{id}
     ~ GET    /api/v1/storefront/vendors/{id}/extra-items
