### Vendor menu [/api/v1/storefront/vendors/{id}/products/{id}]

#### Get all products [GET /api/v1/storefront/vendors/{id}/products]

+ Response 200 (application/json)

        {
            "data": "tba"
        }

#### Get all extra items [GET /api/v1/storefront/vendors/{id}/extra-items]

+ Response 200 (application/json)

        {
            "data": "tba"
        }

#### Get a single product [GET /api/v1/storefront/vendors/{id}/products/{id}]

+ Response 200 (application/json)

        {
            "data": "tba"
        }


