### Vendors [/api/v1/storefront/vendors]

#### Branches [GET /api/v3/storefront/child-vendors]

+ Response 200 (application/json)

        {
            "data": "tba"
        }

#### Branch search [GET /api/v1/storefront/vendors]

@todo: there's also a v2 endpoint.. what's the different and which should we use?

+ Response 200 (application/json)

        {
            "data": "tba"
        }

#### Branch search result count [GET /api/v1/storefront/vendors/count]

+ Response 200 (application/json)

        {
            "data": "tba"
        }

#### Branch details [GET /api/v3/storefront/vendors/{id}]

+ Response 200 (application/json)

        {
            "data": "tba"
        }
